run:
  timeout: 5m

linters:
  enable:
    - govet
    - unused

  disable:
    - gocyclo
    - funlen
    - lll
    - ineffassign
    - stylecheck
    - staticcheck
    - gosimple
    - errcheck

issues:
  exclude-use-default: false