name: ForgeKey

on:
  push:
    branches:
      - main
      - dev-go-version
  pull_request:
    branches:
      - main
      - dev-go-version

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Automatically cancels any currently running workflow in this same group
  cancel-in-progress: true

jobs:
  KEM-Test:
    runs-on: ubuntu-24.04-arm

    defaults:
      run:
        working-directory: go/crypto

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Kyber Key Generation, Encapsulation, Decapsulation
        run: go test -count=1 -v -race -cover ./kem/...

  SHA3-Test:
    runs-on: ubuntu-24.04-arm

    defaults:
      run:
        working-directory: go/crypto

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: SHA3 [SHAKE128, SHAKE256]
        run: go test -count=1 -v -race -cover ./sha3/...

  SIGN-AND-VERIFY-Test:
    runs-on: ubuntu-24.04-arm

    defaults:
      run:
        working-directory: go/crypto

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Dilithium Signature Generation & Verify
        run: go test -count=1 -v -race -cover ./sign/...

  Code-Lint:
    runs-on: ubuntu-24.04-arm
    if: github.event_name == 'pull_request'

    defaults:
      run:
        working-directory: go/crypto

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run lint
        run: golangci-lint run ./...